drop table user_details
drop table user_preferences
drop table order_content
drop table orders
drop table user_carts
drop table items
drop table item_categories
drop table users
drop table user_roles
